### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by kyleaoman** [tberlok/paicos#48]
Will add any comments on dependencies here as I come across them.

To start: the notebook examples depend on matplotlib, which is not a dependency of the package (could be added as an optional dependency) or mentioned in the docs. While most users probably have this installed, I started from a blank virtual environment to catch these sorts of corner cases...

**Comment by kyleaoman** [comment]
There is also an implicit dependency on `ipympl`.

**Comment by tberlok** [comment]
I have added matplotlib as a dependency and now give instructions about ipywidgets in the relevant notebook: https://paicos.readthedocs.io/en/latest/notebooks/notebook6_interactive_visualization_on_the_gpu.html
