### ISSUE TITLE
Community contributions

### ISSUE THREAD

**Issue by ttricco** [tberlok/paicos#57]
I'm doing my JOSS review of Paicos and I can't seem to find any information about how other users can contribute.

It would be great to have explicit statements somewhere about how users:
- could submit code or documentation (do you accept PRs from anyone?)
- notify of bugs or other problems with Paicos (should they use the issue tracker?)
- ask for help using the software (slack? email? issue tracker? go away and leave me alone?)

**Comment by tberlok** [comment]
There is now updated information on the README.md page of the Github repo. https://github.com/tberlok/paicos
The updates were also done following instructions in #47.
